def make_3d_outline_gcode(inner_width, inner_length, height, filename):
    """
    Build a G-code file with:
      - outer rectangle (0,0) to (outer_width, outer_length)
      - inner rectangle inset by `height`
      - from each inner corner: one horizontal + one vertical line outward
        to the outer rectangle (like in the original SVG version)
    All geometry is cut as individual line segments at one depth.

    NOTE: This assumes dimensions are in millimetres and outputs G21.
    """

    # --- Basic machining parameters (tune if you want) ---
    SAFE_Z = 12.7      # mm (0.5 in)
    CUT_DEPTH = -2.54  # mm (-0.1 in) – same magnitude as material Z in your .TAP
    PLUNGE_FEED = 200  # mm/min
    CUT_FEED = 3000    # mm/min

    # Compute outer and inner rectangle coordinates
    # Inner rectangle is offset by `height` from all sides
    # --- Geometry: inner & outer rectangles ---
    # Inner rectangle is offset by `height` from all sides
    ix0, iy0 = height, height
    ix1, iy1 = ix0 + inner_width, iy0 + inner_length

    x0, y0 = 0.0, 0.0
    x1, y1 = inner_width + 2 * height, inner_length + 2 * height

    material_thickness = abs(CUT_DEPTH)

    #filename = f"boxOutline_{inner_width:.3f}x{inner_length:.3f}x{height:.3f}.TAP"
    filename = filename + ".TAP"

    lines = []

    # --- Header ---
    lines.append("(Box outline generated by Python)")
    lines.append(f"(Material Size) (X={x1:.4f}, Y={y1:.4f}, Z={material_thickness:.4f})")
    lines.append(f"G21 G17 G49 G80 G90 G91.1")
    lines.append("M6 T6")
    lines.append("(Tool Number:6) (0.125 inches dia. slot drill)")
    lines.append(f"G43 H6 G0Z{SAFE_Z:.4f}")

    # --- Small helpers to manage continuous paths ---
    def begin_path(x_start, y_start):
        """Rapid to start point at safe Z, then plunge once."""
        lines.append(f"G0 X{x_start:.4f} Y{y_start:.4f} Z{SAFE_Z:.4f}")
        lines.append(f"G1 Z{CUT_DEPTH:.4f} F{PLUNGE_FEED}")

    def line_to(x, y):
        """Cut a line from current point to (x, y) at cutting feed."""
        lines.append(f"G1 X{x:.4f} Y{y:.4f} F{CUT_FEED}")

    def end_path():
        """Retract to safe Z at the end of a path."""
        lines.append(f"G0 Z{SAFE_Z:.4f}")

    # --- Outer rectangle as ONE continuous loop ---
    begin_path(x0, y0)
    line_to(x1, y0)  # bottom edge
    line_to(x1, y1)  # right edge
    line_to(x0, y1)  # top edge
    line_to(x0, y0)  # left edge back to start
    end_path()

    # --- Inner rectangle as ONE continuous loop ---
    begin_path(ix0, iy0)
    line_to(ix1, iy0)  # bottom edge
    line_to(ix1, iy1)  # right edge
    line_to(ix0, iy1)  # top edge
    line_to(ix0, iy0)  # left edge back to start
    end_path()

    # --- Connector lines from inner corners ---
    # Note: each is its own path, because they branch from the corner.

    # Top-left inner corner: horizontal to left, vertical to bottom
    begin_path(ix0, iy0)
    line_to(x0, iy0)   # to left
    end_path()

    begin_path(ix0, iy0)
    line_to(ix0, y0)   # to bottom
    end_path()

    # Top-right inner corner
    begin_path(ix1, iy0)
    line_to(x1, iy0)   # to right
    end_path()

    begin_path(ix1, iy0)
    line_to(ix1, y0)   # to bottom
    end_path()

    # Bottom-right inner corner
    begin_path(ix1, iy1)
    line_to(x1, iy1)   # to right
    end_path()

    begin_path(ix1, iy1)
    line_to(ix1, y1)   # to top
    end_path()

    # Bottom-left inner corner
    begin_path(ix0, iy1)
    line_to(x0, iy1)   # to left
    end_path()

    begin_path(ix0, iy1)
    line_to(ix0, y1)   # to top
    end_path()

    # --- Footer ---
    lines.append(f"G0 Z{SAFE_Z:.4f}")
    lines.append("G0 X0.0000 Y0.0000")
    lines.append("M5")
    lines.append("M30")
    lines.append("")

    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return filename


if __name__ == "__main__":
    width = float(input("Enter the inner width: "))
    length = float(input("Enter the inner length: "))
    height = float(input("Enter the height: "))
    unit = input("Enter the unit: ")
    filename = input("Enter the filename: ")
    if unit in ["in", "inch", "inches"]:
        width *= 25.4
        length *= 25.4
        height *= 25.4
    elif unit in ["mm", "millimeter", "millimeters"]:
        pass
    else:
        print(f"Invalid unit: {unit}")
        exit(1)
    outer_w = width + 2 * height
    outer_l = length + 2 * height
    print(f"Outer size: {outer_w} x {outer_l} {unit}")
    gcode_file = make_3d_outline_gcode(width, length, height, filename)
    print(f"G-code written to: {gcode_file}")
