import os
import tkinter as tk
from tkinter import filedialog, messagebox

def make_3d_outline_gcode(inner_width, inner_length, height, filename_base):
    """
    Build a G-code file with:
      - outer rectangle (0,0) to (outer_width, outer_length)
      - inner rectangle inset by `height`
      - from each inner corner: one horizontal + one vertical line outward
        to the outer rectangle (like in the original SVG version)
    All geometry is cut as individual line segments at one depth.

    NOTE: This assumes dimensions are in millimetres and outputs G21.
    """

    # --- Basic machining parameters (tune if you want) ---
    SAFE_Z = 12.7      # mm (0.5 in)
    CUT_DEPTH = -2.54  # mm (-0.1 in)
    PLUNGE_FEED = 200  # mm/min
    CUT_FEED = 3000    # mm/min

    # Compute outer and inner rectangle coordinates
    ix0, iy0 = height, height
    ix1, iy1 = ix0 + inner_width, iy0 + inner_length

    x0, y0 = 0.0, 0.0
    x1, y1 = inner_width + 2 * height, inner_length + 2 * height

    material_thickness = abs(CUT_DEPTH)

    # filename_base is a full path without extension; append .TAP
    filename = filename_base + ".TAP"

    lines = []

    # --- Header ---
    lines.append("(Box outline generated by Python)")
    lines.append(f"(Material Size) (X={x1:.4f}, Y={y1:.4f}, Z={material_thickness:.4f})")
    lines.append(f"G21 G17 G49 G80 G90 G91.1")
    lines.append("M6 T6")
    lines.append("(Tool Number:6) (0.125 inches dia. slot drill)")
    lines.append(f"G43 H6 G0Z{SAFE_Z:.4f}")

    # --- Small helpers to manage continuous paths ---
    def begin_path(x_start, y_start):
        """Rapid to start point at safe Z, then plunge once."""
        lines.append(f"G0 X{x_start:.4f} Y{y_start:.4f} Z{SAFE_Z:.4f}")
        lines.append(f"G1 Z{CUT_DEPTH:.4f} F{PLUNGE_FEED}")

    def line_to(x, y):
        """Cut a line from current point to (x, y) at cutting feed."""
        lines.append(f"G1 X{x:.4f} Y{y:.4f} F{CUT_FEED}")

    def end_path():
        """Retract to safe Z at the end of a path."""
        lines.append(f"G0 Z{SAFE_Z:.4f}")

    # --- Outer rectangle as ONE continuous loop ---
    begin_path(x0, y0)
    line_to(x1, y0)  # bottom edge
    line_to(x1, y1)  # right edge
    line_to(x0, y1)  # top edge
    line_to(x0, y0)  # left edge back to start
    end_path()

    # --- Inner rectangle as ONE continuous loop ---
    begin_path(ix0, iy0)
    line_to(ix1, iy0)  # bottom edge
    line_to(ix1, iy1)  # right edge
    line_to(ix0, iy1)  # top edge
    line_to(ix0, iy0)  # left edge back to start
    end_path()

    # --- Connector lines from inner corners ---
    # Top-left inner corner: horizontal to left, vertical to bottom
    begin_path(ix0, iy0)
    line_to(x0, iy0)   # to left
    end_path()

    begin_path(ix0, iy0)
    line_to(ix0, y0)   # to bottom
    end_path()

    # Top-right inner corner
    begin_path(ix1, iy0)
    line_to(x1, iy0)   # to right
    end_path()

    begin_path(ix1, iy0)
    line_to(ix1, y0)   # to bottom
    end_path()

    # Bottom-right inner corner
    begin_path(ix1, iy1)
    line_to(x1, iy1)   # to right
    end_path()

    begin_path(ix1, iy1)
    line_to(ix1, y1)   # to top
    end_path()

    # Bottom-left inner corner
    begin_path(ix0, iy1)
    line_to(x0, iy1)   # to left
    end_path()

    begin_path(ix0, iy1)
    line_to(ix0, y1)   # to top
    end_path()

    # --- Footer ---
    lines.append(f"G0 Z{SAFE_Z:.4f}")
    lines.append("G0 X0.0000 Y0.0000")
    lines.append("M5")
    lines.append("M30")
    lines.append("")

    # Actually write the file
    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return filename


# ---------------- Tkinter GUI ---------------- #

class BoxMakerApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Box G-code Generator")

        # Variables
        self.width_var = tk.StringVar()
        self.length_var = tk.StringVar()
        self.height_var = tk.StringVar()
        self.unit_var = tk.StringVar(value="mm")  # default
        self.filename_var = tk.StringVar()
        self.folder_var = tk.StringVar()

        # Layout
        row = 0

        tk.Label(root, text="Inner width:").grid(row=row, column=0, sticky="e", padx=5, pady=5)
        tk.Entry(root, textvariable=self.width_var).grid(row=row, column=1, padx=5, pady=5)

        row += 1
        tk.Label(root, text="Inner length:").grid(row=row, column=0, sticky="e", padx=5, pady=5)
        tk.Entry(root, textvariable=self.length_var).grid(row=row, column=1, padx=5, pady=5)

        row += 1
        tk.Label(root, text="Height (offset):").grid(row=row, column=0, sticky="e", padx=5, pady=5)
        tk.Entry(root, textvariable=self.height_var).grid(row=row, column=1, padx=5, pady=5)

        row += 1
        tk.Label(root, text="Unit:").grid(row=row, column=0, sticky="e", padx=5, pady=5)
        unit_menu = tk.OptionMenu(root, self.unit_var, "mm", "in")
        unit_menu.grid(row=row, column=1, sticky="w", padx=5, pady=5)

        row += 1
        tk.Label(root, text="Filename (without .TAP):").grid(row=row, column=0, sticky="e", padx=5, pady=5)
        tk.Entry(root, textvariable=self.filename_var).grid(row=row, column=1, padx=5, pady=5)

        row += 1
        tk.Label(root, text="Save folder:").grid(row=row, column=0, sticky="e", padx=5, pady=5)
        folder_entry = tk.Entry(root, textvariable=self.folder_var, width=30)
        folder_entry.grid(row=row, column=1, padx=5, pady=5, sticky="w")
        tk.Button(root, text="Browse...", command=self.browse_folder).grid(row=row, column=2, padx=5, pady=5)

        row += 1
        tk.Button(root, text="Generate G-code", command=self.generate_gcode).grid(
            row=row, column=0, columnspan=3, pady=10
        )

    def browse_folder(self):
        folder = filedialog.askdirectory()
        if folder:
            self.folder_var.set(folder)

    def generate_gcode(self):
        # Validate numeric inputs
        try:
            width = float(self.width_var.get())
            length = float(self.length_var.get())
            height = float(self.height_var.get())
        except ValueError:
            messagebox.showerror("Invalid input", "Width, length and height must be numbers.")
            return

        unit = self.unit_var.get()
        filename = self.filename_var.get().strip()
        folder = self.folder_var.get().strip()

        if not filename:
            messagebox.showerror("Missing filename", "Please enter a filename.")
            return

        if not folder:
            messagebox.showerror("Missing folder", "Please choose a folder where the file will be saved.")
            return

        # Normalize filename: remove .tap if user typed it
        if filename.lower().endswith(".tap"):
            filename = filename[:-4]

        # Convert to mm if needed
        if unit == "in":
            width_mm = width * 25.4
            length_mm = length * 25.4
            height_mm = height * 25.4
        elif unit == "mm":
            width_mm = width
            length_mm = length
            height_mm = height
        else:
            messagebox.showerror("Invalid unit", f"Unit '{unit}' is not supported.")
            return

        # Build full path without extension
        filename_base = os.path.join(folder, filename)

        try:
            gcode_path = make_3d_outline_gcode(width_mm, length_mm, height_mm, filename_base)
        except Exception as e:
            messagebox.showerror("Error", f"Failed to generate G-code:\n{e}")
            return

        outer_w = width_mm + 2 * height_mm
        outer_l = length_mm + 2 * height_mm

        messagebox.showinfo(
            "Success",
            f"G-code written to:\n{gcode_path}\n\n"
            f"Outer size (mm): {outer_w:.3f} x {outer_l:.3f}"
        )


if __name__ == "__main__":
    root = tk.Tk()
    app = BoxMakerApp(root)
    root.mainloop()
